In [23]:
import numpy as np
import pandas as pd

In [24]:
df = pd.DataFrame({"num":[6,7,8], "color":["red","green","blue"]}, index=['a','b','c'])
df

   num  color
a    6    red
b    7  green
c    8   blue

In [25]:
# remove the row where num == 6
df.drop(df[df["num"] == 6].index, axis=0, inplace=True)
df

   num  color
b    7  green
c    8   blue

In [26]:
# drops the column name "color"
df.drop("color", axis=1, inplace=True)
df

   num
b    7
c    8